[phases.setup]
nixPkgs = ["nodejs_20", "python3", "buildPackages.gcc"]

[phases.install]
cmds = ["npm run install-all"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node server/index.js"

[variables]
NODE_ENV = "production"
